---
name: Create packages and test installation

on:
  pull_request:

jobs:
  centos7:
    name: Build CentOS 7 RPMs
    runs-on: ubuntu-latest
    container: quay.io/centos/centos:7
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install build requisites
        run: |
          yum install -y rpm-build rpmlint make rsync
      - name: build rpm
        run: |
          make rpm
          rpmlint --file .rpmlint.ini build/RPMS/x86_64/*.rpm
      - name: Upload rpms
        uses: actions/upload-artifact@v3
        with:
          name: rpms7
          path: |
            build/RPMS/x86_64/ui-*.el7.x86_64.rpm

  centos7-install:
    name: Install CentOS 7 RPMs
    needs: centos7
    runs-on: ubuntu-latest
    container: quay.io/centos/centos:7
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: rpms7
      - name: Install generated RPMs
        run: |
          yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
          yum install -y http://repository.egi.eu/sw/production/umd/4/centos7/x86_64/updates/umd-release-4.1.3-1.el7.centos.noarch.rpm
          yum localinstall -y ui-*.rpm
