---
name: Create packages and test installation

on:
  pull_request:

jobs:
  centos7:
    name: Build CentOS 7 RPMs
    runs-on: ubuntu-latest
    container: quay.io/centos/centos:7
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install build requisites
        run: |
          yum install -y rpm-build rpmlint make rsync
      - name: build rpm
        run: |
          make rpm
          rpmlint --file .rpmlint.ini build/RPMS/x86_64/*.rpm
      - name: Upload rpms
        uses: actions/upload-artifact@v3
        with:
          name: rpms7
          path: |
            build/RPMS/x86_64/ui-*.el7.x86_64.rpm

  build-almalinux9:
    name: Build AlmaLinux 9 RPMs
    runs-on: ubuntu-latest
    container: almalinux:9
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install build requisites
        run: |
          dnf install -y rpm-build rpmlint make rsync systemd-rpm-macros
      - name: build rpm
        run: |
          make clean rpm
          rpmlint --file .rpmlint.ini build/RPMS/noarch/*.rpm
      - name: Upload RPMs
        uses: actions/upload-artifact@v3
        with:
          name: rpms9
          path: |
            build/RPMS/x86_64/ui-*.el9.x86_64.rpm

  centos7-install:
    name: Install CentOS 7 RPMs
    needs: centos7
    runs-on: ubuntu-latest
    container: quay.io/centos/centos:7
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: rpms7
      - name: Install generated RPMs
        run: |
          yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
          yum install -y http://repository.egi.eu/sw/production/umd/4/centos7/x86_64/updates/umd-release-4.1.3-1.el7.centos.noarch.rpm
          yum localinstall -y ui-*.rpm

  install-almalinux9:
    name: Install AlmaLinux 9 RPMs
    needs: build-almalinux9
    runs-on: ubuntu-latest
    container: almalinux:9
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: rpms9
      - name: Install generated RPMs
        run: |
          dnf install -y epel-release
          dnf config-manager --add-repo http://repository.egi.eu/sw/production/cas/1/current/repo-files/egi-trustanchors.repo
          # FIXME: Replace WLCG repo by UMD5 once available
          dnf install -y https://linuxsoft.cern.ch/wlcg/el9/x86_64/wlcg-repo-1.0.0-1.el9.noarch.rpm
          dnf config-manager --set-enabled crb
          dnf localinstall -y ui-*.rpm
